## This compose is for building all the images
version: "3.9"

services:
  yt-archive-x86:
    build:
      context: yt-archive/
      dockerfile: Dockerfile
    image: tetricz/yt-archive:amd64
    platform: linux/amd64

  openvpn-client-x86:
    build:
      context: openvpn-client/
      dockerfile: Dockerfile
    image: tetricz/openvpn-client:amd64
    platform: linux/amd64

  yt-archive-arm:
    build:
      context: ./yt-archive/
      dockerfile: Dockerfile
    image: tetricz/yt-archive:arm64
    platform: linux/arm64

  openvpn-client-arm:
    build:
      context: openvpn-client/
      dockerfile: Dockerfile
    image: tetricz/openvpn-client:arm64
    platform: linux/arm64
