pipeline {
    environment{
        AMD64BUILD=''
    }
    agent any
    stages {
        stage('Buildx setup'){
            steps{
                script{
                    sh "docker buildx create --name nextcloud-builder --use"
                    sh "docker buildx inspect --bootstrap"
                }
            }
        }
        stage('Parallel builds'){
            parallel {
                stage('Start AMD64 build'){
                    steps{
                        script{
                            def res = build 'nextcloud-amd64'
                            echo "AMD64 build finished"
                            AMD64BUILD=res.number
                        }
                    }
                    post{
                        failure{
                            echo "AMD64 build failed"
                        }
                    }
                }
            }
        }

        stage('Update manifest'){
            steps{
                script{
                    echo "AMD64BUILD: ${AMD64BUILD}"
                    withCredentials([usernamePassword( credentialsId: 'DockerhubCredentials', usernameVariable: 'USER', passwordVariable: 'PASSWORD')]) {
                        sh "echo $PASSWORD | docker login -u $USER --password-stdin"
                        sh "docker pull tetricz/nextcloud:amd64-build-${AMD64BUILD}"
                        sh "docker manifest create tetricz/nextcloud:latest tetricz/nextcloud:amd64-build-${AMD64BUILD}"
                        sh "docker manifest create tetricz/nextcloud:27 tetricz/nextcloud:amd64-build-${AMD64BUILD}-27"
                        sh "docker manifest create tetricz/nextcloud:26 tetricz/nextcloud:amd64-build-${AMD64BUILD}-26"
                        sh "docker manifest create tetricz/nextcloud:25 tetricz/nextcloud:amd64-build-${AMD64BUILD}-25"
                        sh "docker manifest push tetricz/nextcloud:latest"
                        sh "docker manifest push tetricz/nextcloud:27"
                        sh "docker manifest push tetricz/nextcloud:26"
                        sh "docker manifest push tetricz/nextcloud:25"
                    }
                }
            }
        }
    }
    post {
		always {
            sh 'docker buildx prune --builder=nextcloud-builder -fa'
            sh 'docker buildx rm nextcloud-builder'
            sh "docker manifest rm tetricz/nextcloud:latest"
            sh "docker manifest rm tetricz/nextcloud:27"
            sh "docker manifest rm tetricz/nextcloud:26"
            sh "docker manifest rm tetricz/nextcloud:25"
			sh 'docker logout'
		}
	}
}
