#!/bin/bash
addgroup -g ${GID} minecraft
adduser -g "Minecraft server user" -h "/minecraft" -s "/bin/bash" -D -u ${UID} --ingroup minecraft minecraft

id -u "minecraft"
id -g "minecraft"

# Create eula.txt if one does not exist
if [ ! -e /minecraft/eula.txt ]; then
    echo -e "Generated by $(uname -a)\neula=${EULA}" > /minecraft/eula.txt
fi

# Rather than download the server jar, it's baked into the image
# This statement is to avoid having the persistent volume having outdated jars.
# On the first run, copy the jar to the persistent volume
if [ ! -e /jars/copied ]; then
    cp /jars/*.jar /minecraft/
    cp /minecraft/ferium.log /minecraft/ferium.log.$(date +%s)
    rm -f /minecraft/ferium.log
    touch /jars/copied
fi

chown -R minecraft:minecraft /minecraft

su "minecraft" -c "exec /update.sh"
su "minecraft" -c "exec \"$@\""
