#!/bin/bash
cd /minecraft
# Create eula.txt if one does not exist
if [ ! -e /minecraft/eula.txt ]; then
    echo "Generated by $(uname -a)\neula=${EULA}" > /minecraft/eula.txt
fi

# Rather than download the server jar, it's baked into the image
# This statement is to avoid having the persistent volume having outdated jars.
# On the first run, copy the jar to the persistent volume
if [ ! -e /jars/copied ]; then
    cp /jars/*.jar /minecraft/
    cp /minecraft/ferium.log /minecraft/ferium.log.$(date +%s)
    rm -f /minecraft/ferium.log
    touch /jars/copied
fi

ferium -V
echo "To add mods to run on the host of the container, 'docker exec -it <container> /bin/bash' and then 'ferium add <mod/slug>'"
# print profile, if empty the process will exit with code 1
ferium --config-file "/minecraft/${FERIUM_CONFIG}" profile list
if [ $? -eq 0 ]; then
    echo "Profile exists, skipping"
else
    echo "Profile does not exist, creating"
    ferium --config-file "/minecraft/${FERIUM_CONFIG}" profile create --name "Default" --game-version "${ENV_MC_VERSION}" --mod-loader "${MOD_LOADER}" --output-dir "/minecraft/mods/"
fi
# ensure the profile is correct
ferium --config-file "/minecraft/${FERIUM_CONFIG}" profile configure --name "Default" --game-version "${ENV_MC_VERSION}" --mod-loader "${MOD_LOADER}" --output-dir "/minecraft/mods/"
# update mods with ferium
ferium --config-file "/minecraft/${FERIUM_CONFIG}" upgrade >> /minecraft/ferium.log
# launch the server
java -Xmx${MEMORY} -Xms${MEMORY} -jar fabric-server-launch.jar nogui
